apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: startmeup-dev

resources:
  - ../../startmeup/ns
  - ../../startmeup/app
  - ../../startmeup/db
  - ../../startmeup/pvc
  - ../../startmeup/secret
  - ../../startmeup/svc
  - ../../startmeup/ingress
  - ../../startmeup/configmap
patches:
  - target:
      kind: Ingress
      name: startmeup
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: startmeup-dev.os-ccm.aurin-prod.cloud.edu.au
      - op: replace
        path: /spec/tls/0/hosts/0
        value: startmeup-dev.os-ccm.aurin-prod.cloud.edu.au
        
