apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: startmeup-dev

images:
  - name: umeraltaf/startmeup
    newTag: newTag

resources:
  - ../../../base/startmeup/ns
  - ../../../base/startmeup/app
  - ../../../base/startmeup/db
  - ../../../base/startmeup/pvc
  - ../../../base/startmeup/secret
  - ../../../base/startmeup/svc
  - ../../../base/startmeup/ingress
  - ../../../base/startmeup/configmap

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: startmeup-dev.dev.aurin-prod.cloud.edu.au
      - op: replace
        path: /spec/tls/0/hosts/0
        value: startmeup-dev.dev.aurin-prod.cloud.edu.au
    target:
      kind: Ingress
      name: startmeup
