apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: startmeup-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mumeraltaf/quarkus-startmeup.git
    targetRevision: HEAD
    path: deployment/kubernetes/kustomize/staging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: startmeup-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true