## This is basic continuous integration build for your Quarkus application.

name: Merge to main and push artefacts

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Build Container Image and Push to Repo
        run: ./mvnw clean package -DskipTests=true -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ${{ secrets.QUARKUS_CONTAINER_IMAGE_REGISTRY }}
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.QUARKUS_CONTAINER_IMAGE_USERNAME }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.QUARKUS_CONTAINER_IMAGE_PASSWORD }}
