# This is a basic workflow to help you get started with Actions
name: Hello World

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: cd to startmeup kustomization dir
        run: cd ./test-kustomize
      - run: |
          cat ./kustomization.yaml
      - uses: imranismail/setup-kustomize@v2
      - run: |
          cd ./test-kustomize && kustomize edit set image umeraltaf/startmeup:tests
      - name: GIT commit and push all changed files
      - run: |
          cat ./kustomization.yaml