# This is a basic workflow to help you get started with Actions
name: Hello World

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: AURIN-OFFICE/infra-platform-cd
          ssh-key:  ${{ secrets.CD_DEPLOY_KEY }}
      # Runs a single command using the runners shell
      - name: cd to repo
        run: ls
      - name: add line to readme
        run: echo "test" >> README.md
      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "Umer"
          git config --global user.email "umeraltaf@gmail.com"
          git commit -a -m "test"
          git push