---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: startmeup
  name: pgsql-pvc
  labels:
    app: startmeup
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi